[package]
name = "gameboy_emulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "gb_emu_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "gameboy_emulator"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]